# -*- coding: utf-8 -*-
"""week1_ds_assignment.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gqxR3y0c8oRci8aI_lL_a9QuZbkX_Jln
"""



"""# Section 1: Dataset Introduction
**Dataset Chosen:** Titanic Passenger Data
**Why I chose it:** I chose the Titanic dataset because it is a classic data science dataset that contains a good mix of numerical and categorical variables, making it perfect for performing Exploratory Data Analysis (EDA) and practicing the First-Look Protocol. It has more than 500 rows and 5 columns as required by the assignment guidelines.
"""

import pandas as pd
df = pd.read_csv('train.csv')

"""# **Section 2 :7 commands with interpretations**"""

df.shape

"""### C1: df.shape Interpretation
Our dataset has exactly **891 rows** and **12 columns**. This matches the assignment requirement of having at least 500 rows and 5 columns, providing enough sample data for a reliable exploratory analysis.
"""

df.dtypes

"""### C2: df.dtypes Interpretation
The dataset features a mix of data types:
* **int64**: PassengerId, Survived, Pclass, SibSp, Parch.
* **float64**: Age, Fare.
* **object (text)**: Name, Sex, Ticket, Cabin, Embarked.
All data types align correctly with their structural expectations. Since numerical columns like 'Fare' are floats, it confirms no corrupted text characters are blocking numeric calculations.
"""

df.info()

"""### C3: df.info() Interpretation

This command provides a structural health check of our dataset, specifically tracking the number of non-null (filled) entries across all 12 columns compared to the total 891 rows:

* **Age**: Only has **714 non-null values**, meaning **177 entries are completely missing**. Since about 20% of the data is missing, we can later preserve this column by imputing (filling) it with the median age.
* **Cabin**: Only has **204 non-null values**, meaning **687 entries are missing**. Because over 77% of this column is blank, it is statistically unreliable and should be dropped from the dataset before modeling.
* **Embarked**: Has **889 non-null values**, meaning only **2 entries are missing**. This can easily be fixed by filling those 2 blanks with the most common boarding port (Mode).
* **Data Types**: All other columns have a full count of 891 non-null entries, meaning they have zero missing data and their data types (int64, float64, object) are perfectly aligned with expectations.
"""

df.describe()

"""C4: df.describe() Statistical Interpretation
Dataset Size & Missing Values: The dataset contains records for 891 passengers. The Age column has only 714 entries, indicating 177 missing values that need to be handled.

Survival Rate: The mean for Survived is 0.383, which means only about 38.4% of the passengers survived.

Socioeconomic Status (Pclass): The 50th and 75th percentiles are both 3, indicating that the majority of the passengers were in 3rd class (the lowest/economy class).

Age Demographics: The average passenger age was roughly 29.7 years. The youngest passenger was an infant of 0.42 years (~5 months) and the oldest was 80 years old.

Family Size (SibSp & Parch): More than 50% of the passengers were traveling alone (as the 50% mark for both sibling/spouse and parent/child columns is 0). However, some large families were present, with a maximum of 8 siblings/spouses and 6 parents/children.

Fare Distribution: The average ticket price was 32.20. There is high variance (std of 49.69), and the maximum fare of 512.33 is a significant outlier, considering 75% of the passengers paid 31.00 or less.
"""

df.isnull().sum()

"""C5: df.isnull().sum() Missing Value Analysis
Complete Columns: Key identifying, demographic, and financial columns such as PassengerId, Survived, Pclass, Name, Sex, SibSp, Parch, Ticket, and Fare contain 0 missing values, meaning they are fully populated.

Age (177 Missing Values): Roughly 19.9% of the passenger age data is missing. This will require imputation (e.g., using the median age or group-specific averages) before running most machine learning models.

Cabin (687 Missing Values): A massive 77.1% of the cabin records are missing. Because the majority of this column is empty, it may either need to be dropped or transformed into a binary feature (e.g., Has_Cabin vs No_Cabin).

Embarked (2 Missing Values): Only 2 values are missing. This is a negligible amount and can easily be fixed by imputing them with the mode (most frequent port of embarkation).
"""

df['Survived'].value_counts()

"""C6: df['Survived'].value_counts() Target Variable Analysis
Non-Survivors (0): A total of 549 passengers did not survive the disaster, making up approximately 61.6% of the dataset.

Survivors (1): A total of 342 passengers survived, accounting for approximately 38.4% of the dataset.

Class Balance: The target variable shows a mild class imbalance (roughly a 60:40 split). While there are more non-survivors than survivors, the minority class is large enough that standard classification algorithms should perform well without requiring heavy class-balancing techniques.
"""

df.duplicated().sum()

"""C7: df.duplicated().sum() Duplicate Rows Analysis
Zero Duplicates: The output is 0, which confirms that there are no duplicate rows in the entire dataset.

Data Integrity: Every row represents a unique passenger record, meaning we do not need to perform any data deduplication (such as df.drop_duplicates()) before moving on to feature engineering or modeling.

# Section 3: 20+ Additional EDA Commands
"""

df.head(10)

"""### Interpretation for Command 1 (df.head):
This command displays the first 10 rows of our dataset. It helps us manually visually inspect the data format, column alignments, and see how textual and numerical fields look together in the actual table.
"""

df.tail(5)

"""### Interpretation for Command 2 (df.tail):
This command displays the final 5 rows of the dataset. It allows us to ensure that the dataset did not experience any truncation or corruption at the very end during the file download or loading process.
"""

df.sample(15)

"""### Interpretation for Command 3 (df.sample):
This command extracts 15 completely random rows from the dataset. Sampling random rows is highly useful for checking the data without any ordering bias that might exist in the top or bottom rows.
"""

df.columns.tolist()

"""### Interpretation for Command 4 (df.columns.tolist):
This returns a clean Python list of all 12 column headers. It helps us quickly verify the exact spelling of our column names and check if there are any accidental hidden empty spaces (like 'Fare ') that could cause errors later.
"""

df.nunique()

"""### Interpretation for Command 5 (df.nunique):
This counts the number of unique distinct values in each column. For instance, 'Survived' has 2 unique values (0 and 1) and 'Sex' has 2 (male and female), confirming they are binary categories. Meanwhile, high numbers in 'Ticket' or 'PassengerId' show they act as unique identifiers.
"""

df['Sex'].unique()

"""### Interpretation for Command 6 (df['Sex'].unique):
This command displays the unique categorical entries inside the 'Sex' column, which are exactly ['male', 'female']. This confirms that the gender column is clean and does not contain any corrupt values, duplicates, or typos (like 'mle' or 'fem').
"""

df.corr(numeric_only=True)

"""### Interpretation for Command 7 (df.corr):
This command shows the linear correlation between all numerical features. A key finding here is a positive correlation between 'Fare' and 'Survived', indicating that passengers who paid higher ticket prices had a higher statistical chance of survival (likely due to first-class rescue priority).
"""

df['Age'].hist(bins=20)

"""### Interpretation for Command 8 (df['Age'].hist):
This command visualizes the distribution of passenger ages using a histogram. The graph peaks sharply around the 20 to 30 age range, showing that the majority of people on board were young adults. There is also a small bump near zero, indicating a significant number of infants.
"""

df.groupby('Sex')['Survived'].mean()

"""### Interpretation for Command 9 (df.groupby):
This groups the survival rate by gender. It reveals an extreme disparity: around 74% of females survived, whereas less than 19% of males survived. This strongly reflects the historical maritime protocol of rescuing "women and children first."
"""

df['Embarked'].value_counts(normalize=True)

"""### Interpretation for Command 10 (df['Embarked'].value_counts with normalize):
By setting normalize=True, this command calculates the percentage distribution of the boarding stations. It reveals that over 72% of the passengers boarded from Southampton ('S'), making it the dominant majority port for this voyage.
"""

df.select_dtypes(include='object').head()

"""### Interpretation for Command 11 (df.select_dtypes):
This command filters our dataset to display only the object (text-based) columns, which are 'Name', 'Sex', 'Ticket', 'Cabin', and 'Embarked'. Isolating these text variables allows us to scan for formatting discrepancies or categorical patterns without being distracted by numerical values.
"""

df['Name'].str.contains('Master').sum()

"""### Interpretation for Command 12 (Text Pattern Search):
This command searches the string values inside the 'Name' column to count how many passengers hold the title of 'Master'. It returns a specific count, which gives a proxy for the number of young male children on board, showing how text mining can help engineer demographic features.
"""

df.sort_values('Fare', ascending=False).head(5)

"""### Interpretation for Command 13 (df.sort_values):
This command sorts the dataset by the 'Fare' column in descending order to isolate the top 5 highest paying passengers. This helps identify the extreme outliers who paid £512, confirming that these individuals belonged to the elite first-class upper tier.
"""

df[df['Age'] > 60]

"""### Interpretation for Command 14 (Boolean Filtering):
This command filters the entire DataFrame to isolate passengers who were senior citizens (older than 60 years). Looking at this subset helps us analyze if elderly passengers were given evacuation priority or if they suffered a lower survival rate.
"""

pd.pivot_table(df, values='Survived', index='Pclass', columns='Sex', aggfunc='mean')

"""### Interpretation for Command 15 (pd.pivot_table):
This generates a cross-tabulation table evaluating survival rates simultaneously across passenger classes and gender. It clearly illustrates the combined socioeconomic impact: First-class females had a near 97% survival rate, whereas Third-class males had the lowest odds of survival, proving that class and gender jointly determined a passenger's fate.

# Section 4: Key Findings

Based on our comprehensive Exploratory Data Analysis (EDA) of the Titanic dataset, here are the 3 major key findings:

1. **Socioeconomic Survival Bias:** Passenger class played a critical role in survival odds. The pivot table and descriptive statistics show that First-class passengers, especially females (with a near 97% survival rate), were heavily prioritized during evacuation, whereas Third-class males had the lowest chances of survival.
2. **Severe Missing Data Anomalies:** A deep dive into data health (`df.info()`) revealed that the 'Cabin' column is completely unreliable, missing over 77% of its entries, and should be excluded from future models. However, the 'Age' column (20% missing) is stable enough to be preserved using median imputation.
3. **Extreme Economic Disparity & Outliers:** The ticket 'Fare' feature is heavily right-skewed. While half of the passengers paid less than £14.45, extreme high-end luxury outliers paid up to £512.33. Additionally, the presence of £0.00 fares flags an important business anomaly of complimentary passengers that requires domain cleaning.
"""

